### ISSUE TITLE
PREP-CHEM_SRC

### ISSUE THREAD

**Issue by Nawahda-Amin** [anikfal/atmospheric_science#1]
Dear Dr. Amir
Thank you very much for the great efforts and comprehensive videos on YouTube, I am facing the following error when make OPT=gfortran.wrf CHEM=RADM_WRF_FIM

**### _**cp -f  ../../src/gocart_background.f90 gocart_background.f90
gfortran -c -Xpreprocessor -DRADM_WRF_FIM -O2 -fconvert=big-endian -frecord-marker=4 -fallow-argument-mismatch -fallow-invalid-boz -I../../aux_src/utils/include -I/usr/include -I/usr/include  gocart_background.f90
gocart_background.f90:132:5:

  132 | use netcdf
      |     1
Fatal Error: Cannot open module file ‘netcdf.mod’ for reading at (1): No such file or directory
compilation terminated.
make: *** [depend_prepsrc.mk:450: gocart_background.o] Error 1**_**

Any thoughts about it?
Best Regards,
Amin

**Comment by anikfal** [comment]
Hi Amin,
Have you installed `netcdf` and `gfortran` on your system?
If so, the error is actually self-describing. You need to make `netcdf.mod` available to the program. One workaround can be as follows:
`ln -s /usr/lib64/gfortran/netcdf.mod /usr/include/`

**Comment by Nawahda-Amin** [comment]
Dear Dr. Amir thank you so much for getting back to me
I've followed your suggestion but get the same error, I searched for the netcdf.mod and fond at; 

/home/administrator/Models/WRF-Chem/Downloads/netcdf-fortran-4.6.0/fortran/netcdf.mod
/home/administrator/Models/WRF-Chem/Libs/NETCDF/include/netcdf.mod
/home/administrator/amin/WRFmodel/LIBRARIES/netcdf-fortran-4.5.2/fortran/netcdf.mod
/home/administrator/amin/WRFmodel/LIBRARIES/netcdf/include/netcdf.mod

**Comment by anikfal** [comment]
It seems you have installed netcdf manually. So you need to modify `NETCDF` variable in `include.mk.gfortran.wrf` to the path of your netcdf installation directory. In the video, it is `NETCDF=/usr`, which is for the case that netcdf is installed by the package manager (yum, apt-get, etc).
Be sure that `NETCDF_INC` and `NETCDF_LIBS` are displaying valid paths.

**Comment by Nawahda-Amin** [comment]
Thank you so much solved!
