### ISSUE TITLE
For chemical conversion programs: convert_emiss.exe

### ISSUE THREAD

**Issue by supermh11** [anikfal/atmospheric_science#10]
How to apply convert_emiss.exe to two nested domains, d01 and d02, currently according to your YouTube tutorial only d01, but I found that I do double-layer nesting d02 can not use this conversion program to generate emission files, can I ask you? Thank you very much!

**Comment by anikfal** [comment]
What is double-layer nesting?

As I mentioned in the video, you need to do the same task for all parent and nested domains. After applying `convert_emiss.exe` on d01, modify the namelist accordingly and do the same procedure for d02.

**Comment by supermh11** [comment]
I get it ,thank you！
