### ISSUE TITLE
About WRF operation

### ISSUE THREAD

**Issue by supermh11** [anikfal/atmospheric_science#11]
Hello! I would like to ask you about the two parameters nproc_x and nproc_y, because I am running wrf on a supercomputer, why the following error will be reported whenever I add these two parameters to namelist.input:
```
module_io_quilt_old.F        2931 F
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    6790
ERROR reading namelist domains
-------------------------------------------
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
If I cancel these two parameters, 
I will need to reduce the number of CPU cores to run because the number of cpu cores is too large, but this will cause the running speed to slow down. Do you know how to solve it? Thank you very much!!

**Comment by supermh11** [comment]
I chose 34. (dmpar),Just like your video tutorial, but with two nested domains, I submit a task on a computer cluster to run wrf.exe
By submitting the following shell script
#!/bin/bash
#SBATCH --job-name=wrf_job
#SBATCH --output=wrf_job.out              
#SBATCH --error=wrf_job.err               
#SBATCH --ntasks=72                       
#SBATCH --nodes=2                         
#SBATCH --time=336:00:00                   
#SBATCH --partition=compute
#SBATCH --nodelist=c[08-09]               
#SBATCH --mail-type=END,FAIL  
module load openmpi 
module load netcdf
module load hdf5
    
cd /home/hackd/Build_WRF/WRF/test/em_real

mpirun -np 72 $WRF_EXE

**Comment by supermh11** [comment]
By the way, Professor, I ran wrf.exe according to the same steps as your
WRF-Chem video tutorial, but I received an error in the rsl.out.0000 file.
Strangely, wrf.exe can still run, do you know why? I adjusted time_step
according to the promotion, But the problem still exists, I installed
WRFV4.4, this is an error message:
WARNING: sea salt option 1 currently works only with the GOCART aerosol
option.
start_domain_em: numgas =   50
Timing for Writing wrfout_d01_2022-03-13_00:00:00 for domain 1: 2.31896
elapsed seconds
mediation_integrate: med_read_wrf_chem_emissions: Read emissions for time
2022-03-13_00:00:00
mediation_integrate: med_read_wrf_chem_emissions: Open file
wrfchemi_d01_2022-03-13_00:00:00
d01 2022-03-13_00:00:00  Input data is acceptable to use:
wrfchemi_d01_2022-03-13_00:00:00
d01 2022-03-13_00:00:00  Input data is acceptable to use: wrffirechemi_d01
d01 2022-03-13_00:00:00  Input data is acceptable to use:
wrfchemi_gocart_bg_d01
d01 2022-03-13_00:00:00 Input data processed for aux input   8 for domain
1
d01 2022-03-13_00:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain 1: 1.69716 elapsed seconds
Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     50 JS      1 JE     23
WRF NUMBER OF TILES =   1
d01 2022-03-13_00:00:00  ----------------------------------------
d01 2022-03-13_00:00:00 W-DAMPING BEGINS AT W-courant NUMBER = 1.00000000
d01 2022-03-13_00:00:00  ----------------------------------------
Forced exit from Rosenbrock due to the following error:
Step size too small
T= 7.2000000000000079E-020 and H= 7.2000000000000079E-020
Forced exit from Rosenbrock due to the following error:
Step size too small
T= 5.6328122511434428E-005 and H= 1.8098419647622933E-016
Forced exit from Rosenbrock due to the following error:
Step size too small
T= 7.2000000000000079E-020 and H= 7.2000000000000079E-020
Forced exit from Rosenbrock due to the following error:
Step size too small
T= 7.2000000000000079E-020 and H= 7.2000000000000079E-020
Forced exit from Rosenbrock due to the following error:
Step size too small
T= 7.2000000000000079E-020 and H= 7.2000000000000079E-020
Forced exit from Rosenbrock due to the following error:
Step size too small

Can you answer my question? Thank you very much!

Amirhossein Nikfal ***@***.***> 于2024年7月11日周四 20:38写道：

**Comment by anikfal** [comment]
Try to run the model with `chem_opt=0` and by commenting out emissions parameters (`auxinput5_inname` and `io_form_auxinput5`) to see if the same error occurs again or not.

Also you can decrease `time_step` to 70% of its current value and try running again.

**Comment by supermh11** [comment]
The previous problem did not occur when you said chem_opt=0 and commented out auxinput5_inname and io_form_auxinput5.
Both rsl.out.0000 and rsl.error.0000 show the following:
Timing for main: time 2022-03-13_23:58:30 on domain   1:    0.63709 elapsed seconds
Timing for main: time 2022-03-13_23:59:00 on domain   1:    0.63792 elapsed seconds
Timing for main: time 2022-03-13_23:59:30 on domain   1:    0.63595 elapsed seconds
Timing for main: time 2022-03-14_00:00:00 on domain   1:    0.63928 elapsed seconds
Timing for Writing wrfout_d01_2022-03-14_00:00:00 for domain        1:    1.96813 elapsed seconds
d01 2022-03-14_00:00:00 wrf: SUCCESS COMPLETE WRF

rsl.out.0000 and rsl.error.0000 file output the same content.But my final wish is to realize the operation of WRF-Chem, because I mainly want to learn WRF-Chem. Do you have any good solutions

**Comment by anikfal** [comment]
Modify the chem options with regard to this [nameslit](https://github.com/anikfal/atmospheric_science/blob/main/wrfchem_tools/prep_chem_sources/namelist.input) and run again.
