### ISSUE TITLE
grid_type in set_prepchem_input.sh

### ISSUE THREAD

**Issue by yliu-yb** [anikfal/atmospheric_science#12]
Dose grid_type only surpport 'lambert'?
 /grid_type/ s/.*=.*/grid_type='lambert',/

**Comment by anikfal** [comment]
Different types of projections which are available in WPS are discussed in the [WRF user guide](https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_V3/user_guide_V3.9/contents.html):
1. polar stereographic
2. Lambert-Conformal
3. Mercator
4. latitude-longitude

**Comment by yliu-yb** [comment]
However, the script(set_prepchem_input.sh) does not read the projection type from namelist.wps; instead, it directly specifies it as Lambert. If I use a non-Lambert projection in namelist.wps, it will cause an error. Is it possible to set it to read the projection type from namelist.wps in the future?

**Comment by anikfal** [comment]
Yes, it assumes the grid type as Lambert. If you change the grid type to another type, other parameters of the namelist must also be changed.

May I know the reason you didn't choose the Lambert projection?

I'll try to develop the code to support other projections as well. Thanks for your report.

PS WRF visualizations can be done by PostWRF for all grid types.
