### ISSUE TITLE
parameter setting in set_prepchem_input.sh

### ISSUE THREAD

**Issue by yliu-yb** [anikfal/atmospheric_science#13]
I found that the set_prepchem_input.sh script does not modify the following parameters, but these parameters  in prep_chem_sources.inp provided on GitHub are not the default values. 
Parameters in prep_chem_sources.inp : nlat, lon_beg, lat_beg, delta_lon, delta_lat.
Do we need to manually modify these parameters?

The default values:
nlat=320,          ! if gg (only global grid)
lon_beg   = -180., ! (-180.:+180.) long-begin of the output file
lat_beg   =  -90., ! ( -90.:+90. ) lat -begin of the output file
delta_lon =  360, ! total long extension of the domain (360 for global)
delta_lat =  180, ! total lat  extension of the domain (180 for global)

The parameters in your GitHub are：
 nlat=192,          ! if gg (only global grid)
 lon_beg   =  50, ! (-180.:+180.) long-begin of the output file
 lat_beg   =  30, ! ( -90.:+90. ) lat -begin of the output file
 delta_lon =  120., ! total long extension of the domain (360 for global)
 delta_lat =  70., ! total lat  extension of the domain (180 for global)

**Comment by anikfal** [comment]
Not all parameters in `prep_chem_sources.inp` are needed to be modified. Actually the script `set_prepchem_input.sh` assumes that the grid projection is Lambert. So the parameters which are not related to this projection (e.g. global grid) are not modified.

**Comment by yliu-yb** [comment]
I just looked at the documentation, and different projections correspond to different grid settings. Thank you very much!

I've been following the tutorial you posted on YouTube, and I encountered an error when running convert_emiss.exe. I've been unable to resolve it and hope to get your help.

**Comment by yliu-yb** [comment]
I successfully ran convert_emiss after updating WRF from version 3.9.1 to 4.6.
Thank you very much!
