### ISSUE TITLE
CO2 simulation

### ISSUE THREAD

**Issue by supermh11** [anikfal/atmospheric_science#14]
Hello, may I ask you about the operation of WRF-GHG (chem_opt=17) simulation of CO2? Why did I input the anthropogenic emission file and get 0 CO2 variable in operation? Or did I choose the wrong chemical option? Are there any other chemical options available for CO2 simulation study

**Comment by anikfal** [comment]
Hi. You must use special settings for CO2, such as `chem_opt=16` or `emiss_opt=16`. Moreover, you must be sure that the emissions for CO2 are properly created.

**Comment by supermh11** [comment]
yes,CO2 emission file can be read, I was through the official processing
tool: ANTHRO, processing, according to the reason should be no problem, but
all the variables running out are 0, this is my error document.

Amirhossein Nikfal ***@***.***> 于2024年9月9日周一 18:56写道：

**Comment by anikfal** [comment]
If emissions data for CO2 are okay, then the namelist settings must have some issues. You can check them again according to the WRF user guide.

**Comment by supermh11** [comment]
Ok, thank you for your reply. Your answer has benefited me a lot. I
rechecked the emission file and found that the variable was named
incorrectly. It's been solved now.

Amirhossein Nikfal ***@***.***> 于2024年9月10日周二 03:49写道：
