### ISSUE TITLE
mozbc.inp: the "spc_map" parameter is empty

### ISSUE THREAD

**Issue by yliu-yb** [anikfal/atmospheric_science#15]
hello

**I executed ./set_mozbc_input.sh and got the following output:**

 ```
Be sure you have already run WRF real.exe successfully with chem_opt=301, 302, ...
------SUCCESSFUL!------
mozbc.inp has been successfully created!
Now run the command below to make boundary values in wrfinput and wrfbdy files
./mozbc < mozbc.inp > mozbc.out
```

**However, I checked mozbc.inp and found that the spc_map parameter is empty.**
```
&control

do_bc     = .true.
do_ic     = .true.
domain = 1
dir_wrf = '/wind1/home/liuy2593/wrf/WRF/test/em_real_task1/'
dir_moz = '/wind1/home/liuy2593/wrf/MOZBC/'
fn_moz  = 'waccm-20241009214026877633.nc'
moz_var_suffix  = ''

spc_map =
/
```
**How should I resolve this issue?
PS: I successfully completed all the steps before the MOZBC tutorial, following your series of video tutorials.**

**Comment by yliu-yb** [comment]
**When I executed the following command:**
`ncl_filedump $wrfdir/wrfinput_d01.nc | grep float > wrfinput_vars.txt
`
**I found that the content of wrfinput_vars.txt is all as follows:**
`Type: float 
Type: float
Type: float
Type: float
Type: float
...
`
**with no variable names listed. Is this normal?**

**Comment by yliu-yb** [comment]
**The output format from ncl_filedump wrfinput_d01.nc is as follows:**
```
Variable: o3
    Type: float
    Total Size: 12540 values
                50160 bytes
    Number of Dimensions: 4
    Dimensions and sizes:	[ 1 <Time | unlimited> x 44 <bottom_top> x 15 <south_north> x 19 <west_east> ]
    Chunking Info:	[ 1 <Time> x 44 <bottom_top> x 8 <south_north> x 10 <west_east> ]
    Coordinates:
        Number of Attributes:        6
            FieldType	: 	104
            MemoryOrder	: 	XYZ
            description	: 	O3 mixing ratio
            units	: 	ppmv
            stagger	: 	
            coordinates	: 	XLONG XLAT XTIME
```
However, the format obtained from ncl_filedump waccm-20241009214026877633.nc is as follows:
```
      float CO ( time, lev, lat, lon )
         mdims :	1
         units :	mol/mol
         mixing_ratio :	dry
         long_name :	CO concentration
```

**I am using WRF version 4.6.0, and perhaps the difference in version is causing the file format of wrfinput_d01.nc to be different, which in turn is preventing the command ncl_filedump $wrfdir/wrfinput_d01.nc | grep float > wrfinput_vars.txt from properly obtaining variable names?**

**Comment by anikfal** [comment]
`set_mozbc_input.sh` can be effective, only if all `wrfbdy`, `wrfinput_d0*`, and `waccm-20241009214026877633.nc` contain the same emissions data in separate variables.

For example, let's say we want to generate the boundary conditions for the variable `NO2`. In such a case, this variable should exist in `wrfinput_d01`, `wrfbdy`, and `waccm-20241009214026877633.nc` files. Otherwise, running `set_mozbc_input.sh` cannot update the boundary values inside the WRF input files, even if `NO2` exists inside `waccm-20241009214026877633.nc`.

**Comment by yliu-yb** [comment]
**I changed the line in the script set_mozbc_input.sh from:**
`ncl_filedump $wrfdir/wrfinput_d01.nc | grep float > wrfinput_vars.txt`
to:
`ncdump -h $wrfdir/wrfinput_d01 | grep "float" | awk '{print $1, $2}' > wrfinput_vars.txt`

**My wrfinput_vars.txt will contain the following variables instead of just "Type: float"**
`float so2(Time,
float sulf(Time,
float no2(Time,
float no(Time,
float o3(Time,
float hno3(Time,
float h2o2(Time,
float ald(Time,
float hcho(Time,
float op1(Time,
float op2(Time,
float paa(Time,
float ora1(Time,
float ora2(Time,
float nh3(Time,
float n2o5(Time,
float no3(Time,
float pan(Time,
float hc3(Time,
float hc5(Time,
float hc8(Time,
float eth(Time,
float co(Time,
`
**Then, I modified `grep "float $wrfvar (" wrfinput_vars.txt 1>/dev/null `to `grep "float $wrfvar(" wrfinput_vars.txt 1>/dev/null`**

**After that, I followed your tutorial video, and everything went smoothly in the end.**

[mozbc.out.txt](https://github.com/user-attachments/files/17327254/mozbc.out.txt)
