### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sageerabbas1** [anikfal/atmospheric_science#3]
while running./ungrib.exe

`./ungrib.exe: /11b/x86_64-11nux-gnu//1bpng12.so.0: verston *PNG12_0' not found (requtred by •/ungrib.exe)`

**Comment by anikfal** [comment]
Hi,
Please make issues with clear subject and enough explanations. Indeed GitHub issues are different from Google search bar!

The error is likely due to the libpng library. Perhaps it is not installed. Before running WPS, you need to install its prerequisite libraries, such as libpng and jasper.
