### ISSUE TITLE
AFTER running metgrid this error is shown

### ISSUE THREAD

**Issue by sageerabbas1** [anikfal/atmospheric_science#4]
ubuntu@hydro-layer:~/WRFmodel/WPS$ ./metgrid.exe
Processing domain 1 of 1
 Processing 2016-05-18_00
    PL
    SFC
WARNING: Field PRES has missing values at level 200100 at (i,j)=(55,26)
WARNING: Field PMSL has missing values at level 200100 at (i,j)=(55,26)
WARNING: Field PSFC has missing values at level 200100 at (i,j)=(55,26)
WARNING: Field SOILHGT has missing values at level 200100 at (i,j)=(55,26)
WARNING: Field GHT has missing values at level 200100 at (i,j)=(55,26)
ERROR: Missing values encountered in interpolated fields. Stopping.
Note: The following floating-point exceptions are signalling: IEEE_OVERFLOW_FLAG

**Comment by anikfal** [comment]
The domain of the ungrib data (ERA5, FNL, etc) should be larger that your WRF (WPS) domain. Otherwise this error may occur.

For example if the ranges of your WRF domain are 40E-50E and 30N-40N, the downloaded met data should be (e.g.) 1 degree extended: 39E-51E and 29N-41N

**Comment by sageerabbas1** [comment]
how i can define  domain and nested domain ranges,currently i am in learning stage and for practice i want to make parent domain from 65E to 82E and 20N TO 34N and my study area as rajasthan india as nested domain 22N to 32N ,69E to 79E

**Comment by anikfal** [comment]
You can check online documentations:
https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/contents.html
My training videos:
https://youtube.com/playlist?list=PL93HaRiv5QkBw_k3chrXX3pVYcOlXJiQ7&si=0xCXGrzckxhER1JV
And perhaps many other resources.
