### ISSUE TITLE
Error running metgrid for ECMWF IFS (ds113.1- NCAR-RDA) data

### ISSUE THREAD

**Issue by prakriti3896** [anikfal/atmospheric_science#5]
I successfully completed the geogrid and ungrib of the .pl and .sfc files separately using the Vtable.ECMWF . In &metgrid i changed the prefix to PL for pressure level data and SFC for Surface data. In &metgrid i changed fg_name = 'PL', 'SFC' . After ungribbing all the files when I run Metgrid I get the following error- 

Processing domain 1 of 3

 Processing 2021-12-01_00
    PL
Oops, something is not right with the Gaussian latitude computation.
The input data gave the starting latitude as   37.996.
This routine computed the starting latitude as +-  89.946.
The difference is larger than 0.01 degrees, which is not expected.
ERROR: Gaussian_latitude_computation
Abort(0) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0

PS: I used data subset, I've run wrf with subset of different data like fnl or gdas.

I am attaching the metgrid

[namelist.wps.txt](https://github.com/anikfal/atmospheric_science/files/14571267/namelist.wps.txt)
[metgrid.log](https://github.com/anikfal/atmospheric_science/files/14571269/metgrid.log)

**Comment by anikfal** [comment]
Be sure that your WRF domain extents are fully covered by the ECMWF data.
