### ISSUE TITLE
mozbc does not modify wrfinput files

### ISSUE THREAD

**Issue by prakriti3896** [anikfal/atmospheric_science#7]
Hello, 
I am running mozbc for 1 month data and the start & end time of wrf is for the same month. I have downloaded the waccm file of 31 days for Dec 2021 and same time is defined in my namelist.input . When I run set_mozbc_input.sh , it runs successfully but when I open the mozbc.inp file it does not have  anything in spc_map.
if I manually write the spc name in the mozbc.inp file then if I run the utility there is no changes in the concentration values of wrfinput file. 

maybe utility is unable to view the variables in my wrfinput files. i am using wrfv4.4 , not sure if mozbc works with new version. 

I am attaching my mozbc.inp file, namelist.input, set_mozbc_input.sh, waccm_vars.txt, wrfinput_vars.txt, and also the screenshot of the variables available in my wrfinput file: 
![Variables](https://github.com/anikfal/atmospheric_science/assets/149140938/5a6b1d3c-09c1-4252-b2ed-281de8d7c6c9)

[mozbc_input.txt](https://github.com/anikfal/atmospheric_science/files/14692844/mozbc_input.txt)
[waccm_vars.txt](https://github.com/anikfal/atmospheric_science/files/14692859/waccm_vars.txt)
[wrfinput_vars.txt](https://github.com/anikfal/atmospheric_science/files/14692861/wrfinput_vars.txt)
[namelist.input.txt](https://github.com/anikfal/atmospheric_science/files/14692955/namelist.input.txt)
[set_mozbc_input.txt](https://github.com/anikfal/atmospheric_science/files/14692976/set_mozbc_input.txt)

**Comment by anikfal** [comment]
Hi,
Can you please send me this waccm file? I'll try to investigate the issue.
