### ISSUE TITLE
About mozbc

### ISSUE THREAD

**Issue by supermh11** [anikfal/atmospheric_science#9]
![52624253-0C94-48CC-B9B0-DED1AEF27954](https://github.com/anikfal/atmospheric_science/assets/172979052/a6b6c492-a98a-4445-88aa-fe19bc004f51)
Hello, I watched your video on YouTube and followed your steps, but this problem has occurred in mozbc.inp. Could you please ask how to solve this problem? I will thank you very much.

**Comment by anikfal** [comment]
Hi
Can you check what variables are inside your `waccm` file? To do so, you can run the command below on your `waccmfile.nc`:
`ncdump -h waccmfile.nc`

**Comment by supermh11** [comment]
Sorry for the late reply. Is it because this waccmfile variable is not familiar with the variable of the sh file you provided? This is my waccmfile output variable, you can have a look at it. Thank you.
[Uploading output.txt…]()

**Comment by anikfal** [comment]
There are a list of variables which can be extracted. But maybe the variables are not available in your waccmfile. Or maybe they are different.

The link of the file you sent seems to be broken. I couldn't get it.

**Comment by supermh11** [comment]
You can try this [output.txt](https://github.com/user-attachments/files/15864151/output.txt)

**Comment by anikfal** [comment]
The variables inside the waccm file are basically used to update the same variables inside the wrfinput file. For example inside the waccm file you have `C2H4` variable. You should have the same variable inside your wrfinput file, so mozbc can update it by the variable provided by waccmfile.
So it seems none of the variables inside your waccmfile are available in your wrfinput file. You can check it by doing the same task you did (ncdump ...) on your wrfinput file.

**Comment by supermh11** [comment]
I see what you mean, thank you! I'm a newbie and your video is very useful! This is the file that I extracted the wrfinput variable from, let's say the wrfinput file variable is the same as waccmfile. What do you do when the variables don't agree
[wrfinput_output.txt](https://github.com/user-attachments/files/15864709/wrfinput_output.txt)
